apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vjx3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vjx3
    app.kubernetes.io/part-of: tkrw-pr712-0075-0019-app
  name: devfile-sample-vjx3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vjx3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vjx3
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-vjx3@sha256:a8b64facb6aa23f66ed9b3c392ccf6a9e089347f6968e2a9120ddb31cce25566
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
